include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    prefer_typing_uninitialized_variables: ignore
