targets:
  $default:
    builders:
      freezed:
        options:
          explicit_to_json: true
      json_serializable:
        options:
          # field_rename: snake
          explicit_to_json: true